// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateUrl(ctx context.Context, arg CreateUrlParams) (CreateUrlRow, error)
	GetUrlByShort(ctx context.Context, shortUrl string) (GetUrlByShortRow, error)
	IncrementClickCount(ctx context.Context, shortUrl string) (IncrementClickCountRow, error)
}

var _ Querier = (*Queries)(nil)
