// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: url.sql

package db

import (
	"context"
)

const createUrl = `-- name: CreateUrl :one
INSERT INTO urls (original_url, short_url)
VALUES ($1, $2)
RETURNING id, original_url, short_url, created_at, updated_at
`

type CreateUrlParams struct {
	OriginalUrl string
	ShortUrl    string
}

func (q *Queries) CreateUrl(ctx context.Context, arg CreateUrlParams) (Url, error) {
	row := q.db.QueryRow(ctx, createUrl, arg.OriginalUrl, arg.ShortUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUrlByShort = `-- name: GetUrlByShort :one
SELECT id, original_url, short_url, created_at, updated_at
FROM urls
WHERE short_url = $1
`

func (q *Queries) GetUrlByShort(ctx context.Context, shortUrl string) (Url, error) {
	row := q.db.QueryRow(ctx, getUrlByShort, shortUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
